### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by castlemas**
@caramelmelmel review pls :D

### CODE REVIEW

**Comment by Fishbiscuit** [comment]
Create a new repository instead so this can be archived and name it DiscoverSUTD-2021

**Comment by castlemas** [comment]
@caramelmelmel @jamestiotio @Fishbiscuit  Do merge

**Comment by caramelmelmel** [comment]
LGTM!

**Comment by jamestiotio** [comment]
Hi @caramelmelmel! As requested by @Fishbiscuit, the DiscoverSUTD 2021 Microsite fork has been ported over to [another separate repository](https://github.com/OpenSUTD/DiscoverSUTD-2021-microsite) instead.

Following this action, this PR will be closed.

**Pull request closed without merging**
